# Generated by Django 4.2.10 on 2024-08-31 19:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['username'], name='username_idx'), models.Index(fields=['first_name'], name='first_name_idx'), models.Index(fields=['last_name'], name='last_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('groupname', models.CharField(max_length=32, unique=True)),
                ('users', models.ManyToManyField(blank=True, related_name='telegram_groups', to='telegram.telegramuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramGroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('user_id', models.BigIntegerField()),
                ('reply_to_msg_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram.telegramgroup')),
            ],
            options={
                'indexes': [models.Index(fields=['message_id'], name='message_id_idx'), models.Index(fields=['date'], name='date_idx'), models.Index(fields=['reply_to_msg_id'], name='reply_to_msg_id_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='telegramgroupmessage',
            constraint=models.UniqueConstraint(fields=('telegram_group', 'message_id'), name='unique_telegram_group_message_id'),
        ),
    ]
