# Generated by Django 4.2.10 on 2024-08-31 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramgroupmessage',
            name='user_id',
        ),
        migrations.AddField(
            model_name='telegramgroupmessage',
            name='user',
            field=models.ForeignKey(default=7100526176, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram.telegramuser'),
            preserve_default=False,
        ),
    ]
