# Generated by Django 4.2.10 on 2024-02-26 05:25

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramgroup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='telegramgroup',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
