# Generated by Django 4.2.10 on 2024-08-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_telegramclient_listenertelegramgroup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramclient',
            old_name='client_session',
            new_name='session',
        ),
    ]
