# Generated by Django 4.2.10 on 2024-08-31 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_remove_telegramgroupmessage_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='telegramgroupmessage',
            name='date_idx',
        ),
    ]
