# Generated by Django 4.2.10 on 2024-02-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_remove_telegramgroup_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramgroup',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='json_file',
            field=models.FileField(blank=True, null=True, upload_to='telegram_json'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='session_file',
            field=models.FileField(blank=True, null=True, upload_to='telegram_sessions'),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
