# Generated by Django 4.2.10 on 2024-09-01 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_remove_telegramgroupmessage_date_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroupmessage',
            name='telegram_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_messages', to='telegram.telegramgroup'),
        ),
        migrations.AlterField(
            model_name='telegramgroupmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_messages', to='telegram.telegramuser'),
        ),
    ]
