# Generated by Django 4.2.10 on 2024-08-29 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djelethon', '0001_initial'),
        ('telegram', '0003_rename_client_session_telegramclient_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramclient',
            name='api_hash',
        ),
        migrations.RemoveField(
            model_name='telegramclient',
            name='api_id',
        ),
        migrations.AddField(
            model_name='telegramclient',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djelethon.app'),
        ),
        migrations.AlterField(
            model_name='telegramclient',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djelethon.clientsession'),
        ),
    ]
