# Generated by Django 4.2.10 on 2024-09-01 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_alter_telegramgroupmessage_telegram_group_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='telegramgroupmessage',
            name='unique_telegram_group_message_id',
        ),
        migrations.RemoveField(
            model_name='telegramgroup',
            name='users',
        ),
        migrations.RemoveField(
            model_name='telegramgroupmessage',
            name='telegram_group',
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groups', to='telegram.telegramuser'),
        ),
        migrations.AddField(
            model_name='telegramgroupmessage',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram.telegramgroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramgroupmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram.telegramuser'),
        ),
        migrations.AddIndex(
            model_name='telegramgroup',
            index=models.Index(fields=['groupname'], name='groupname_idx'),
        ),
        migrations.AddConstraint(
            model_name='telegramgroupmessage',
            constraint=models.UniqueConstraint(fields=('group', 'message_id'), name='group_message_id_unique'),
        ),
    ]
