# Generated by Django 4.2.10 on 2024-02-28 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_telethon', '0001_initial'),
        ('telegram', '0004_telegramuser_is_active_telegramuser_proxy_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='json_file',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='session_file',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_telethon.app'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='app_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_telethon.clientsession'),
            preserve_default=False,
        ),
    ]
