# Generated by Django 4.2.10 on 2024-08-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_remove_telegramclient_api_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramclient',
            name='app_json',
        ),
    ]
