# Generated by Django 4.2.10 on 2024-09-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_remove_telegramgroupmessage_unique_telegram_group_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='sex',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Male'), (0, 'Female')], null=True),
        ),
    ]
