# Generated by Django 4.2.10 on 2024-08-29 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djelethon', '0001_initial'),
        ('telegram', '0005_remove_telegramclient_app_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramclient',
            name='session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='djelethon.clientsession'),
        ),
    ]
