# Generated by Django 5.0.2 on 2024-02-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_remove_telegramuser_json_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUserUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_field', models.FileField(upload_to='telegram_json')),
                ('session_file', models.FileField(upload_to='telegram_json')),
            ],
        ),
    ]
