# Generated by Django 4.2.10 on 2024-08-29 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_alter_telegramclient_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramClient',
        ),
    ]
