# Generated by Django 5.0.2 on 2024-02-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_telegramuserupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroup',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='telegramuserupload',
            name='session_file',
            field=models.FileField(upload_to='telegram_session'),
        ),
    ]
