# Generated by Django 4.2.10 on 2024-09-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_telegramuser_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='lang_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
