# Generated by Django 5.0.2 on 2024-03-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0007_telegramgroup_name_alter_telegramgroup_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramUserUpload',
        ),
    ]
