# Generated by Django 4.2.10 on 2024-09-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0008_telegramuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroup',
            name='id',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
