# Generated by Django 5.0.2 on 2024-03-01 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0009_alter_telegramuser_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='session',
            new_name='client_session',
        ),
    ]
