# Generated by Django 4.2.10 on 2024-03-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0011_telegramgroupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='error',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
