# Generated by Django 4.2.10 on 2024-09-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0011_telegramgroup_g_id_alter_telegramgroup_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramgroup',
            name='g_id',
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
