# Generated by Django 4.2.10 on 2024-09-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0012_remove_telegramgroup_g_id_alter_telegramgroup_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='telegramgroup',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
    ]
