# Generated by Django 4.2.10 on 2024-09-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0013_telegramgroup_name_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='telegramgroupmessage',
            name='reply_to_msg_id_idx',
        ),
        migrations.RenameField(
            model_name='telegramgroupmessage',
            old_name='reply_to_msg_id',
            new_name='reply_to_msg',
        ),
    ]
