# Generated by Django 4.2.10 on 2024-03-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0014_telegramuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='two_fa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
