# Generated by Django 4.2.10 on 2024-09-06 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0015_alter_telegramgroupmessage_reply_to_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroupmessage',
            name='reply_to_msg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='telegram.telegramgroupmessage'),
        ),
    ]
