# Generated by Django 4.2.10 on 2024-03-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0016_alter_telegramuser_phone_alter_telegramuser_two_fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='two_fa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
