# Generated by Django 4.2.10 on 2024-09-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0016_alter_telegramgroupmessage_reply_to_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramgroup',
            name='members',
        ),
    ]
