# Generated by Django 4.2.10 on 2024-09-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0017_remove_telegramgroup_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groups', to='telegram.telegramuser'),
        ),
    ]
