# Generated by Django 4.2.10 on 2024-03-19 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_telethon', '0001_initial'),
        ('proxies', '0007_alter_proxyserver_error'),
        ('telegram', '0017_alter_telegramuser_phone_alter_telegramuser_two_fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='app',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_telethon.app'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='client_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_telethon.clientsession'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='proxy_server',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_user', to='proxies.proxyserver'),
        ),
    ]
