# Generated by Django 4.2.10 on 2024-03-19 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0007_alter_proxyserver_error'),
        ('telegram', '0018_alter_telegramuser_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='proxy_server',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user', to='proxies.proxyserver'),
        ),
    ]
