# Generated by Django 4.2.10 on 2024-03-19 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_telethon', '0001_initial'),
        ('telegram', '0019_alter_telegramuser_proxy_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_telethon.app'),
        ),
    ]
