# Generated by Django 4.2.10 on 2024-03-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0020_alter_telegramuser_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroupmessage',
            name='reply_to_msg_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
