# Generated by Django 4.2.10 on 2024-03-21 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0021_alter_telegramgroupmessage_reply_to_msg_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramgroupmessage',
            old_name='message',
            new_name='text',
        ),
        migrations.AlterUniqueTogether(
            name='telegramgroupmessage',
            unique_together={('group', 'message_id')},
        ),
    ]
