# Generated by Django 4.2.10 on 2024-03-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0022_rename_message_telegramgroupmessage_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroupmessage',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
