# Generated by Django 4.2.10 on 2024-03-21 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0023_alter_telegramgroupmessage_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='telegramgroupmessage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='telegramgroupmessage',
            name='telegram_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram.telegramgroup'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='telegramgroupmessage',
            unique_together={('telegram_group', 'message_id')},
        ),
        migrations.RemoveField(
            model_name='telegramgroupmessage',
            name='group',
        ),
    ]
