# Generated by Django 4.2.10 on 2024-03-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0024_alter_telegramgroupmessage_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='sex',
            field=models.PositiveIntegerField(choices=[('Male', 0), ('Feale', 1), ('None', 2)], default=2),
        ),
    ]
