# Generated by Django 4.2.10 on 2024-03-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0027_alter_telegramuser_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='sex',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True),
        ),
    ]
