# Generated by Django 4.2.10 on 2024-03-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0028_alter_telegramuser_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramgroupmessage',
            options={'ordering': ['date']},
        ),
    ]
