# Generated by Django 4.2.10 on 2024-03-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0029_alter_telegramgroupmessage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
