# Generated by Django 4.2.10 on 2024-03-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0030_alter_telegramuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroup',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
