# Generated by Django 4.2.10 on 2024-03-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0031_alter_telegramgroup_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramgroupmessage',
            options={},
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='groups',
            field=models.ManyToManyField(related_name='telegram_users', to='telegram.telegramgroup'),
        ),
    ]
