# Generated by Django 4.2.10 on 2024-03-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0032_alter_telegramgroupmessage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='groups',
            new_name='telegram_groups',
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
