# Generated by Django 4.2.10 on 2024-03-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_telethon', '0001_initial'),
        ('telegram', '0001_squashed_0033_rename_groups_telegramuser_telegram_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='telegramgroupmessage',
            name='telegram_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram.telegramgroup'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='client_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_telethon.clientsession'),
        ),
    ]
