# Generated by Django 4.2.10 on 2024-03-25 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_telethon', '0001_initial'),
        ('telegram', '0034_alter_telegramgroup_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='client_session',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_telethon.clientsession'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='telegram_users', to='telegram.telegramgroup'),
        ),
    ]
