# Generated by Django 4.2.10 on 2024-03-25 12:35

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('telegram', '0035_alter_telegramuser_client_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroup',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
