# Generated by Django 4.2.10 on 2024-03-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0039_alter_telegramgroup_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroupmessage',
            name='text',
            field=models.TextField(db_index=True),
        ),
    ]
