# Generated by Django 4.2.10 on 2024-04-01 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0040_alter_telegramgroupmessage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroup',
            name='similar_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram.telegramgroup'),
        ),
    ]
