# Generated by Django 4.2.10 on 2024-04-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0041_telegramgroup_similar_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramgroup',
            name='similar_group',
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='similar_groups',
            field=models.ManyToManyField(blank=True, null=True, to='telegram.telegramgroup'),
        ),
    ]
