# Generated by Django 4.2.10 on 2024-04-02 18:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0042_remove_telegramgroup_similar_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroupDialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('time', models.DateTimeField()),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramgroupmessage')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
