# Generated by Django 4.2.10 on 2024-04-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0043_telegramgroupdialog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramgroupdialog',
            old_name='time',
            new_name='date',
        ),
    ]
