# Generated by Django 4.2.10 on 2024-04-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0044_rename_time_telegramgroupdialog_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramgroupdialog',
            old_name='group',
            new_name='telegram_group',
        ),
    ]
