# Generated by Django 4.2.10 on 2024-04-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0045_rename_group_telegramgroupdialog_telegram_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='telegramgroupdialog',
            unique_together={('telegram_group', 'dialog')},
        ),
    ]
