# Generated by Django 4.2.10 on 2024-04-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0046_alter_telegramgroupdialog_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramGroupDialog',
        ),
    ]
