# Generated by Django 4.2.10 on 2024-09-08 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proxies', '0003_rename_error_proxyserver_errors'),
        ('djelethon', '0001_initial'),
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('two_fa', models.CharField(max_length=30)),
                ('errors', models.TextField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djelethon.app')),
                ('proxy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='proxies.proxyserver')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djelethon.clientsession')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='telegram_users.telegramuser')),
            ],
        ),
    ]
