# Generated by Django 4.2.10 on 2024-08-29 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0001_initial'),
        ('djelethon', '0001_initial'),
        ('telegram', '0007_delete_telegramclient'),
        ('telegram_clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=30)),
                ('two_fa', models.CharField(max_length=30)),
                ('error', models.TextField(blank=True, null=True)),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djelethon.app')),
                ('proxy_server', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_client', to='proxies.proxyserver')),
                ('session', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='djelethon.clientsession')),
                ('telegram_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_client', to='telegram.telegramuser')),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
