# Generated by Django 4.2.10 on 2024-09-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramclient',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
