# Generated by Django 4.2.10 on 2024-09-01 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_remove_telegramgroupmessage_unique_telegram_group_message_id_and_more'),
        ('proxies', '0001_initial'),
        ('telegram_clients', '0002_alter_telegramclient_app_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramclient',
            name='proxy_server',
        ),
        migrations.RemoveField(
            model_name='telegramclient',
            name='telegram_user',
        ),
        migrations.AddField(
            model_name='telegramclient',
            name='proxy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='proxies.proxyserver'),
        ),
        migrations.AddField(
            model_name='telegramclient',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='telegram.telegramuser'),
            preserve_default=False,
        ),
    ]
