# Generated by Django 4.2.10 on 2024-09-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_clients', '0002_alter_telegramclient_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramclient',
            name='last_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
