# Generated by Django 4.2.10 on 2024-09-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_clients', '0003_remove_telegramclient_proxy_server_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramclient',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
