# Generated by Django 4.2.10 on 2024-09-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_clients', '0003_telegramclient_last_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramclient',
            name='is_listener',
            field=models.BooleanField(default=False),
        ),
    ]
