# Generated by Django 4.2.10 on 2024-09-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_clients', '0004_alter_telegramclient_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramclient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
