# Generated by Django 4.2.10 on 2024-09-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_clients', '0005_alter_telegramclient_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramclient',
            name='phone',
        ),
    ]
