# Generated by Django 4.2.10 on 2024-09-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_clients', '0006_remove_telegramclient_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramclient',
            old_name='error',
            new_name='errors',
        ),
    ]
