# Generated by Django 4.2.10 on 2024-10-01 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_groups', '0001_initial'),
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram_groups.telegramgroup')),
                ('reply_to_msg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='telegram_messages.telegramgroupmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram_users.telegramuser')),
            ],
            options={
                'indexes': [models.Index(fields=['message_id'], name='message_id_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='telegramgroupmessage',
            constraint=models.UniqueConstraint(fields=('group', 'message_id'), name='group_message_id_unique'),
        ),
    ]
