version: '3.4'

services:
  postgres:
    image: postgres:12.12-alpine
    container_name: postgres
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    env_file:
      - ./.env

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend/staticfiles:/home/app/backend/staticfiles
      - ./backend/mediafiles:/home/app/backend/mediafiles
    expose:
      - 8000
    entrypoint: poetry run bash entrypoint.sh
    command: poetry run gunicorn core.wsgi:application --bind 0.0.0.0:8000


  # flower:
  #   build:
  #     context: ./backend
  #     dockerfile: ./Dockerfile
  #   command: celery -A backend flower
  #   volumes:
  #     - .:/home/app
  #   ports:
  #     - 5555:5555

  celery_sheduler:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    depends_on:
      - backend
      - redis
    command: poetry run celery -A core beat -l info


  celery_worker:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    depends_on:
      - backend
      - redis
    command: poetry run celery -A core worker -l info


  nginx:
    container_name: nginx
    build:
      context:  nginx/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

      - ./backend/staticfiles:/home/app/backend/staticfiles
      - ./backend/mediafiles:/home/app/backend/mediafiles
    depends_on:
      - backend
