version: "3.4"

services:
  postgres:
    image: postgres:12.12-alpine
    container_name: postgres
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    # volumes:
    #   - ./redis/d–∞ta:/root/redis
    #   - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - ./.env

  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/home/app/backend
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    entrypoint: poetry run bash entrypoint.sh
    command: poetry run python manage.py runserver 0.0.0.0:8000

  flower:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: poetry run celery -A backend flower
    volumes:
      - .:/home/app
    ports:
      - 5555:5555
    depends_on:
      - postgres
      - redis

  celery_sheduler:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/home/app/backend
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
    command: poetry run celery -A core beat -l info

  celery_worker:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./backend:/home/app/backend
    depends_on:
      - postgres
      - redis
    command: poetry run celery -A core worker -l info
