# Generated by Django 4.2.10 on 2024-09-23 16:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('groupname', models.CharField(max_length=32, unique=True)),
                ('members', models.ManyToManyField(blank=True, related_name='groups', to='telegram_users.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramGroupSource',
            fields=[
                ('telegramgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telegram_groups.telegramgroup')),
                ('is_active', models.BooleanField(default=False)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('listeners', models.ManyToManyField(blank=True, related_name='listener_sources', to='telegram_users.listeneruser')),
            ],
            options={
                'abstract': False,
            },
            bases=('telegram_groups.telegramgroup',),
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TelegramGroupDrain',
            fields=[
                ('telegramgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telegram_groups.telegramgroup')),
                ('is_active', models.BooleanField(default=False)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('actors', models.ManyToManyField(blank=True, related_name='actor_drains', to='telegram_users.actoruser')),
                ('sources', models.ManyToManyField(blank=True, related_name='drains', to='telegram_groups.telegramgroupsource')),
            ],
            options={
                'abstract': False,
            },
            bases=('telegram_groups.telegramgroup',),
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='telegramgroup',
            index=models.Index(fields=['groupname'], name='groupname_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramgroup',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
    ]
