# Generated by Django 4.2.10 on 2024-09-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('telegram_users', '0002_baseclientuser'),
        ('telegram_groups', '0003_telegramgroupdrain_last_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroupsource',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='actor_sources', through='roles.TelegramGroupRole', to='telegram_users.actoruser'),
        ),
    ]
