# Generated by Django 4.2.10 on 2024-09-10 14:21

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_groups', '0004_telegramgroupsource_actors'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='telegramgroupdrain',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='telegramgroupsource',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
