# Generated by Django 4.2.10 on 2024-09-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0002_baseclientuser'),
        ('telegram_groups', '0005_alter_telegramgroupdrain_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroupdrain',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='actor_drains', to='telegram_users.actoruser'),
        ),
    ]
