# Generated by Django 4.2.10 on 2024-09-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_groups', '0006_telegramgroupdrain_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramgroupsource',
            name='actors',
        ),
    ]
