# Generated by Django 4.2.10 on 2024-09-01 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram', '0005_remove_telegramgroupmessage_unique_telegram_group_message_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroupSource',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('telegram.telegramgroup',),
        ),
        migrations.CreateModel(
            name='TelegramGroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='telegram.telegramuser')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='sources.telegramgroupsource')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramuser')),
            ],
        ),
        migrations.AddConstraint(
            model_name='telegramgrouprole',
            constraint=models.UniqueConstraint(fields=('group', 'member', 'actor'), name='group_member_actor_unique'),
        ),
    ]
