# Generated by Django 4.2.10 on 2024-09-03 18:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_telegramuser_sex'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgrouprole',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='telegramgrouprole',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='telegramgrouprole',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_roles', to='telegram.telegramuser'),
        ),
        migrations.AlterField(
            model_name='telegramgrouprole',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_roles', to='telegram.telegramuser'),
        ),
    ]
