# Generated by Django 4.2.10 on 2024-09-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0016_alter_telegramgroupmessage_reply_to_msg'),
        ('sources', '0002_telegramgrouprole_created_telegramgrouprole_modified_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramGroupSource',
        ),
        migrations.CreateModel(
            name='ActorUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('telegram.telegramuser',),
        ),
        migrations.CreateModel(
            name='MemberUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('telegram.telegramuser',),
        ),
        migrations.RemoveConstraint(
            model_name='telegramgrouprole',
            name='group_member_actor_unique',
        ),
        migrations.AddConstraint(
            model_name='telegramgrouprole',
            constraint=models.UniqueConstraint(fields=('group', 'member'), name='group_member_unique'),
        ),
        migrations.AddConstraint(
            model_name='telegramgrouprole',
            constraint=models.UniqueConstraint(fields=('group', 'actor'), name='group_actor_unique'),
        ),
        migrations.AlterField(
            model_name='telegramgrouprole',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_roles', to='sources.actoruser'),
        ),
        migrations.AlterField(
            model_name='telegramgrouprole',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_roles', to='sources.memberuser'),
        ),
        migrations.CreateModel(
            name='TelegramGroupSource',
            fields=[
                ('telegramgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telegram.telegramgroup')),
                ('listeners', models.ManyToManyField(related_name='sources', to='sources.memberuser')),
            ],
            options={
                'abstract': False,
            },
            bases=('telegram.telegramgroup',),
        ),
        migrations.AlterField(
            model_name='TelegramGroupRole',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='sources.telegramgroupsource'),
        ),
    ]
