# Generated by Django 4.2.10 on 2024-09-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_delete_telegramgroupsource_actoruser_memberuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramgroupsource',
            name='listeners',
        ),
    ]
