# Generated by Django 4.2.10 on 2024-09-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_remove_telegramgroupsource_listeners'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroupsource',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groups', to='sources.memberuser'),
        ),
    ]
