# Generated by Django 4.2.10 on 2024-09-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0017_remove_telegramgroup_members'),
        ('sources', '0005_telegramgroupsource_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenerUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('telegram.telegramuser',),
        ),
        migrations.AddField(
            model_name='telegramgroupsource',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='actor_sources', through='sources.TelegramGroupRole', to='sources.actoruser'),
        ),
        migrations.AddField(
            model_name='telegramgroupsource',
            name='errors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramgroupsource',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_sources', to='sources.memberuser'),
        ),
        migrations.AddField(
            model_name='telegramgroupsource',
            name='listeners',
            field=models.ManyToManyField(blank=True, related_name='listener_sources', to='sources.listeneruser'),
        ),
    ]
