# Generated by Django 4.2.10 on 2024-09-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_listeneruser_telegramgroupsource_actors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramgroupsource',
            name='members',
        ),
    ]
