# Generated by Django 4.2.10 on 2024-02-26 05:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='dialogs.dialog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('role', models.CharField(choices=[(1, 'role-1'), (2, 'role-2'), (3, 'role-3'), (4, 'role-4'), (5, 'role-5'), (6, 'role-6'), (7, 'role-7'), (8, 'role-8'), (9, 'role-9'), (10, 'role-10'), (11, 'role-11'), (12, 'role-12'), (13, 'role-13'), (14, 'role-14'), (15, 'role-15'), (16, 'role-16'), (17, 'role-17'), (18, 'role-18'), (19, 'role-19'), (20, 'role-20')], max_length=255)),
                ('text', models.TextField()),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dialogs.dialog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('role', models.CharField(choices=[(1, 'role-1'), (2, 'role-2'), (3, 'role-3'), (4, 'role-4'), (5, 'role-5'), (6, 'role-6'), (7, 'role-7'), (8, 'role-8'), (9, 'role-9'), (10, 'role-10'), (11, 'role-11'), (12, 'role-12'), (13, 'role-13'), (14, 'role-14'), (15, 'role-15'), (16, 'role-16'), (17, 'role-17'), (18, 'role-18'), (19, 'role-19'), (20, 'role-20')], max_length=255)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='dialogs.scene')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramuser')),
            ],
            options={
                'unique_together': {('scene', 'telegram_user', 'role')},
            },
        ),
    ]
