# Generated by Django 4.2.10 on 2024-03-25 08:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    replaces = [('dialogs', '0001_initial'), ('dialogs', '0002_scene_group'), ('dialogs', '0003_alter_message_role_alter_role_role'), ('dialogs', '0004_remove_scene_name'), ('dialogs', '0005_scene_is_active'), ('dialogs', '0006_alter_role_telegram_user'), ('dialogs', '0007_scene_error'), ('dialogs', '0008_alter_scene_error'), ('dialogs', '0009_dialog_is_active'), ('dialogs', '0010_message_reply_to_msg'), ('dialogs', '0011_rename_group_scene_telegram_group_alter_message_role_and_more'), ('dialogs', '0012_alter_message_role_alter_role_role'), ('dialogs', '0013_message_time'), ('dialogs', '0014_dialog_tags_alter_role_role'), ('dialogs', '0015_rename_role_role_name_alter_role_unique_together'), ('dialogs', '0016_remove_message_role_message_role_name_and_more'), ('dialogs', '0017_alter_message_time'), ('dialogs', '0018_remove_dialog_tags'), ('dialogs', '0019_scene_start_date_alter_scene_unique_together'), ('dialogs', '0020_rename_time_message_start_time_and_more'), ('dialogs', '0021_alter_message_unique_together'), ('dialogs', '0022_alter_scene_is_active')]

    initial = True

    dependencies = [
        ('telegram', '0011_telegramgroupmessage'),
        ('telegram', '0001_initial'),
        ('telegram', '0028_alter_telegramuser_sex'),
        ('telegram', '0002_remove_telegramgroup_created_at_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('telegram', '0025_telegramuser_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='dialogs.dialog')),
                ('telegram_group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramgroup')),
                ('is_active', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
                'unique_together': {('dialog', 'telegram_group')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='dialogs.scene')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='telegram.telegramuser')),
            ],
            options={
                'unique_together': {('scene', 'telegram_user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField()),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dialogs.dialog')),
                ('reply_to_msg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dialogs.message')),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('role_name', models.CharField(default='Smbd', max_length=255)),
            ],
            options={
                'abstract': False,
                'unique_together': set(),
            },
        ),
    ]
