# Generated by Django 4.2.10 on 2024-10-01 19:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_groups', '0001_initial'),
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=False)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='dialogs.dialog')),
                ('drain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='telegram_groups.telegramgroupdrain')),
            ],
        ),
        migrations.CreateModel(
            name='DialogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('role_name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('delay', models.DurationField(default=datetime.timedelta(0))),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dialogs.dialog')),
                ('reply_to_msg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dialogs.dialogmessage')),
            ],
        ),
        migrations.CreateModel(
            name='SceneRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_roles', to='telegram_users.actoruser')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='dialogs.scene')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='scene_role_name_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='scenerole',
            constraint=models.UniqueConstraint(fields=('scene', 'name'), name='scene_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='scenerole',
            constraint=models.UniqueConstraint(fields=('scene', 'actor'), name='scene_actor_unique'),
        ),
        migrations.AddConstraint(
            model_name='scene',
            constraint=models.UniqueConstraint(fields=('dialog', 'drain'), name='dialog_drain_unique'),
        ),
    ]
