# Generated by Django 4.2.10 on 2024-09-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scene',
            old_name='error',
            new_name='errors',
        ),
    ]
