# Generated by Django 4.2.10 on 2024-02-26 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_remove_telegramgroup_created_at_and_more'),
        ('dialogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramgroup'),
            preserve_default=False,
        ),
    ]
