# Generated by Django 4.2.10 on 2024-09-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='telegram_group',
        ),
        migrations.DeleteModel(
            name='TelegramGroupRole',
        ),
    ]
