# Generated by Django 4.2.10 on 2024-09-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0002_remove_dialog_telegram_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(),
        ),
    ]
