# Generated by Django 4.2.10 on 2024-02-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0002_scene_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, 'role-1'), (2, 'role-2'), (3, 'role-3'), (4, 'role-4'), (5, 'role-5'), (6, 'role-6'), (7, 'role-7'), (8, 'role-8'), (9, 'role-9'), (10, 'role-10'), (11, 'role-11'), (12, 'role-12'), (13, 'role-13'), (14, 'role-14'), (15, 'role-15'), (16, 'role-16'), (17, 'role-17'), (18, 'role-18'), (19, 'role-19'), (20, 'role-20')]),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, 'role-1'), (2, 'role-2'), (3, 'role-3'), (4, 'role-4'), (5, 'role-5'), (6, 'role-6'), (7, 'role-7'), (8, 'role-8'), (9, 'role-9'), (10, 'role-10'), (11, 'role-11'), (12, 'role-12'), (13, 'role-13'), (14, 'role-14'), (15, 'role-15'), (16, 'role-16'), (17, 'role-17'), (18, 'role-18'), (19, 'role-19'), (20, 'role-20')]),
        ),
    ]
