# Generated by Django 4.2.10 on 2024-09-10 15:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_groups', '0005_alter_telegramgroupdrain_managers_and_more'),
        ('telegram_users', '0002_baseclientuser'),
        ('dialogs', '0003_alter_message_role_name_alter_message_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Message',
            new_name='DialogMessage',
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='role',
            name='scene',
        ),
        migrations.RemoveField(
            model_name='role',
            name='telegram_user',
        ),
        migrations.AlterUniqueTogether(
            name='scene',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scene',
            name='drain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='telegram_groups.telegramgroupdrain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scene',
            name='last_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='scene',
            constraint=models.UniqueConstraint(fields=('dialog', 'drain'), name='dialog_drain_unique'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='scenerole',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='telegram_users.actoruser'),
        ),
        migrations.AddField(
            model_name='scenerole',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='dialogs.scene'),
        ),
        migrations.RemoveField(
            model_name='scene',
            name='telegram_group',
        ),
        migrations.AddConstraint(
            model_name='scenerole',
            constraint=models.UniqueConstraint(fields=('scene', 'name', 'actor'), name='scene_name_actor_unique'),
        ),
    ]
