# Generated by Django 4.2.10 on 2024-02-26 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0003_alter_message_role_alter_role_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='name',
        ),
    ]
