# Generated by Django 4.2.10 on 2024-04-07 06:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
        ('dialogs', '0003_alter_message_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dialog',
            name='telegram_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramgroup'),
        ),
        migrations.DeleteModel(
            name='TelegramGroupDialog',
        ),
    ]
