# Generated by Django 5.0.2 on 2024-03-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0004_remove_scene_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
