# Generated by Django 4.2.10 on 2024-09-10 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0002_baseclientuser'),
        ('dialogs', '0004_scenerole_rename_message_dialogmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenerole',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_roles', to='telegram_users.actoruser'),
        ),
    ]
