# Generated by Django 4.2.10 on 2024-08-27 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_telegramclient_listenertelegramgroup_and_more'),
        ('dialogs', '0005_telegramgrouprole'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgrouprole',
            name='telegram_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.listenertelegramgroup'),
        ),
        migrations.AddField(
            model_name='telegramgrouprole',
            name='telegram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramuser'),
        ),
        migrations.AddConstraint(
            model_name='telegramgrouprole',
            constraint=models.UniqueConstraint(fields=('telegram_group', 'name', 'telegram_user'), name='telegram_group_name_telegram_user_unique'),
        ),
    ]
