# Generated by Django 4.2.10 on 2024-09-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0005_alter_scenerole_actor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialogmessage',
            old_name='start_time',
            new_name='delay',
        ),
    ]
