# Generated by Django 4.2.10 on 2024-09-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0006_rename_start_time_dialogmessage_delay'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scenerole',
            index=models.Index(fields=['name'], name='scene_role_name_idx'),
        ),
    ]
