# Generated by Django 4.2.10 on 2024-03-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0006_alter_role_telegram_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='error',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
