# Generated by Django 4.2.10 on 2024-03-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0007_scene_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
