# Generated by Django 4.2.10 on 2024-09-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0007_scenerole_scene_role_name_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scenerole',
            name='scene_name_actor_unique',
        ),
        migrations.AddConstraint(
            model_name='scenerole',
            constraint=models.UniqueConstraint(fields=('scene', 'name'), name='scene_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='scenerole',
            constraint=models.UniqueConstraint(fields=('scene', 'actor'), name='scene_actor_unique'),
        ),
    ]
