# Generated by Django 4.2.10 on 2024-09-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0008_remove_scenerole_scene_name_actor_unique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='date',
        ),
    ]
