# Generated by Django 4.2.10 on 2024-03-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0008_alter_scene_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
