# Generated by Django 4.2.10 on 2024-03-21 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0009_dialog_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_to_msg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dialogs.message'),
        ),
    ]
