# Generated by Django 4.2.10 on 2024-09-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_groups', '0007_remove_telegramgroupsource_actors'),
        ('dialogs', '0010_alter_dialogmessage_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='drain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='telegram_groups.telegramgroupdrain'),
        ),
    ]
