# Generated by Django 4.2.10 on 2024-03-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0011_rename_group_scene_telegram_group_alter_message_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.PositiveBigIntegerField(choices=[(1, 'Role 1'), (2, 'Role 2'), (3, 'Role 3'), (4, 'Role 4'), (5, 'Role 5'), (6, 'Role 6'), (7, 'Role 7'), (8, 'Role 8'), (9, 'Role 9'), (10, 'Role 10'), (11, 'Role 11'), (12, 'Role 12'), (13, 'Role 13'), (14, 'Role 14'), (15, 'Role 15'), (16, 'Role 16'), (17, 'Role 17'), (18, 'Role 18'), (19, 'Role 19'), (20, 'Role 20')]),
        ),
    ]
