# Generated by Django 4.2.10 on 2024-03-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0012_alter_message_role_alter_role_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.TimeField(default='14:30:15'),
            preserve_default=False,
        ),
    ]
