# Generated by Django 4.2.10 on 2024-03-22 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0016_remove_message_role_message_role_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
