# Generated by Django 4.2.10 on 2024-03-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0017_alter_message_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='tags',
        ),
    ]
