# Generated by Django 4.2.10 on 2024-03-23 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0028_alter_telegramuser_sex'),
        ('dialogs', '0018_remove_dialog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='scene',
            unique_together={('dialog', 'telegram_group')},
        ),
    ]
