# Generated by Django 4.2.10 on 2024-03-24 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0020_rename_time_message_start_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set(),
        ),
    ]
