# Generated by Django 4.2.10 on 2024-03-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0021_alter_message_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
