# Generated by Django 4.2.10 on 2024-04-03 13:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import taggit.managers


class Migration(migrations.Migration):

    replaces = [('dialogs', '0023_alter_message_role_name_alter_scene_telegram_group'), ('dialogs', '0024_dialog_tags'), ('dialogs', '0025_alter_dialog_name_alter_message_role_name_and_more'), ('dialogs', '0026_message_telegram_group'), ('dialogs', '0027_remove_message_telegram_group_dialog_telegram_group'), ('dialogs', '0028_rename_telegram_group_dialog_from_telegram_group'), ('dialogs', '0029_remove_dialog_from_telegram_group'), ('dialogs', '0030_telegramgroupdialog'), ('dialogs', '0031_alter_message_role_name')]

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('telegram', '0042_remove_telegramgroup_similar_group_and_more'),
        ('telegram', '0034_alter_telegramgroup_name_and_more'),
        ('telegram', '0047_delete_telegramgroupdialog'),
        ('dialogs', '0001_squashed_0022_alter_scene_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scene',
            name='telegram_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramgroup'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='role_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name='TelegramGroupDialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateTimeField()),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogs.dialog')),
                ('telegram_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramgroup')),
            ],
            options={
                'unique_together': {('telegram_group', 'dialog')},
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='role_name',
            field=models.CharField(db_index=True, default='Smbd', max_length=255),
        ),
    ]
