# Generated by Django 4.2.10 on 2024-03-25 13:05

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('dialogs', '0023_alter_message_role_name_alter_scene_telegram_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
