# Generated by Django 4.2.10 on 2024-04-01 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0042_remove_telegramgroup_similar_group_and_more'),
        ('dialogs', '0025_alter_dialog_name_alter_message_role_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='telegram_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramgroup'),
        ),
    ]
