# Generated by Django 4.2.10 on 2024-04-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0027_remove_message_telegram_group_dialog_telegram_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialog',
            old_name='telegram_group',
            new_name='from_telegram_group',
        ),
    ]
