# Generated by Django 4.2.10 on 2024-04-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0028_rename_telegram_group_dialog_from_telegram_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='from_telegram_group',
        ),
    ]
