# Generated by Django 4.2.10 on 2024-04-03 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0023_alter_message_role_name_alter_scene_telegram_group_squashed_0031_alter_message_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroupdialog',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_dialogs', to='dialogs.dialog'),
        ),
    ]
