# Generated by Django 4.2.10 on 2024-09-07 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram', '0017_remove_telegramgroup_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroupDrain',
            fields=[
                ('telegramgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telegram.telegramgroup')),
            ],
            options={
                'abstract': False,
            },
            bases=('telegram.telegramgroup',),
        ),
    ]
