# Generated by Django 4.2.10 on 2024-09-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0007_remove_telegramgroupsource_members'),
        ('drains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroupdrain',
            name='errors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramgroupdrain',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telegramgroupdrain',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='drains', to='sources.telegramgroupsource'),
        ),
    ]
