# Generated by Django 5.0.2 on 2024-03-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUserUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_field', models.FileField(upload_to='telegram_json')),
                ('session_file', models.FileField(upload_to='telegram_session')),
            ],
        ),
    ]
