# Generated by Django 4.2.10 on 2024-03-05 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramUserUpload',
            new_name='TelegramUserImport',
        ),
    ]
