# Generated by Django 4.2.10 on 2024-09-08 11:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_groups', '0001_initial'),
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_roles', to='telegram_users.actoruser')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='telegram_groups.telegramgroupsource')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_roles', to='telegram_users.memberuser')),
            ],
        ),
        migrations.AddConstraint(
            model_name='telegramgrouprole',
            constraint=models.UniqueConstraint(fields=('group', 'member'), name='group_member_unique'),
        ),
        migrations.AddConstraint(
            model_name='telegramgrouprole',
            constraint=models.UniqueConstraint(fields=('group', 'actor'), name='group_actor_unique'),
        ),
    ]
