# Generated by Django 4.2.10 on 2024-09-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramgrouprole',
            old_name='group',
            new_name='source',
        ),
    ]
