# Generated by Django 4.2.10 on 2024-09-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_remove_telegramgrouprole_group_member_unique_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramgrouprole',
            old_name='source',
            new_name='group',
        ),
    ]
