# Generated by Django 4.2.10 on 2024-09-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_rename_source_telegramgrouprole_group'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='telegramgrouprole',
            name='group_member_unique',
        ),
        migrations.RemoveConstraint(
            model_name='telegramgrouprole',
            name='source_actor_unique',
        ),
        migrations.AddConstraint(
            model_name='telegramgrouprole',
            constraint=models.UniqueConstraint(fields=('group', 'member'), name='group_member_unique'),
        ),
        migrations.AddConstraint(
            model_name='telegramgrouprole',
            constraint=models.UniqueConstraint(fields=('group', 'actor'), name='group_actor_unique'),
        ),
    ]
