# Generated by Django 4.2.10 on 2024-03-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telethonupdt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatestateclient',
            name='entity_id',
            field=models.BigIntegerField(),
        ),
    ]
