# Generated by Django 4.2.10 on 2024-03-24 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_telethon', '0001_initial'),
        ('telethonupdt', '0002_alter_updatestateclient_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatestateclient',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='update_state_client', to='django_telethon.updatestate'),
        ),
    ]
