# Generated by Django 5.0.2 on 2024-02-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxyserver',
            old_name='server',
            new_name='address',
        ),
        migrations.AddField(
            model_name='proxyserver',
            name='type',
            field=models.CharField(default='socks5', max_length=10),
        ),
    ]
