# Generated by Django 4.2.10 on 2024-09-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0002_alter_proxyserver_protocol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxyserver',
            old_name='error',
            new_name='errors',
        ),
    ]
