# Generated by Django 5.0.2 on 2024-03-01 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0002_rename_server_proxyserver_address_proxyserver_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxyserver',
            old_name='type',
            new_name='protocol',
        ),
    ]
