# Generated by Django 5.0.2 on 2024-03-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0003_rename_type_proxyserver_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyserver',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
