# Generated by Django 4.2.10 on 2024-03-10 18:43

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0004_alter_proxyserver_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyserver',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='proxyserver',
            name='info_check_proxy',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proxyserver',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
