# Generated by Django 4.2.10 on 2024-03-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0006_remove_proxyserver_info_check_proxy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyserver',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
