# Generated by Django 4.2.10 on 2024-03-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0007_alter_proxyserver_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyserver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
