# Generated by Django 4.2.10 on 2024-03-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0008_alter_proxyserver_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyserver',
            name='address',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
