name: Deploy to staging
on:
  push:
    branches:
      - staging

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.STAGING_SSH_HOST }}
        username: ${{ secrets.STAGING_SSH_USERNAME }}
        password: ${{ secrets.STAGING_SSH_PASSWORD }}
        script: |
          cd /home/Shop/
          git pull origin staging && git checkout staging
          docker-compose -f docker-compose.prod.yml up --build -d --remove-orphans
          docker system prune -f


  # Send_notification:
  #   name: Send telegram notification
  #   runs-on: ubuntu-latest
  #   needs: [Deploy]
  #   steps:
  #     - name: Send message
  #       uses: appleboy/telegram-action@master
  #       with:
  #         to: ${{ secrets.TELEGRAM_TO }}
  #         token: ${{ secrets.TELEGRAM_TOKEN }}
  #         message: ${{ github.workflow }} done!
