name: Run tests

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Install the project dependencies
        run: cd backend && poetry install
      - name: Run the automated tests (for example)
        run: cd backend && poetry run python manage.py test
