name: Run tests

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      # -
      #   name: Install the project dependencies
      #   run: cd backend && poetry install
      # - 
      #   name: Run the automated tests (for example)
      #   run: cd backend && poetry run python manage.py test
